# docker-compose file
version: '3.8'

services:
  cultribe:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: cultribe
    platform: linux/amd64
    container_name: cultribe
    image: cultribe:latest
    volumes:
      -.:/app
    ports:
      -8000:8000

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    platform: linux/amd64
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      -"5433:5432"
    volumes:
      -.:/data


